### ISSUE TITLE
Can savemedia be used with Pin as well as 'Snap' ?

### ISSUE THREAD

**Issue by Marxsal** [buggyj/savemedia#3]
Pinning might be even more important than snapping. So can savemedia be used with Pin as well as 'Snap' ?

Thanks!

**Comment by buggyj** [comment]
a snap produces a new image which can be many kilobytes, a pin only produces a link to a image on the web, which is a few bytes.

**Comment by Marxsal** [comment]
I didn't phrase that well. What I meant was that could there be a Pin that saved the image itself to the local drive? Rather than a screenshot, which may not capture the full resolution of the original image.

**Comment by buggyj** [comment]
That is no way to do that in tiddlyclip that I can think of. It is possible to right click on an image and save to a location on disk. It is then possible to clip the local file address with tiddlyclip, this can be done with different media such as pdfs as well. There is a description for pdfs here:

https://github.com/buggyj/tiddlyclip-plugin/discussions/48

I can give some more details if you like.

**Comment by Marxsal** [comment]
The pdf example used something called 'localtwpdf' . Is there something similar for images? When I try to right-click and pin I just end up with a tiddler "Index of directory blah/blah" . The link to the image isn't used.

Thanks!

**Comment by buggyj** [comment]
![image](https://user-images.githubusercontent.com/2855795/151223435-0f166464-51d4-4629-96c8-718dff1b251d.png)

# here are the tids

[localtwpng.json.zip](https://github.com/buggyj/savemedia/files/7944627/localtwpng.json.zip)

**Comment by Marxsal** [comment]
Is "application/x-bclip" something new? The prior TITLETID used a complicated JSON-like structure. This format is much more readable. The other local rule didn't use 'sublink' . What does sublink do?

Thank you!

**Comment by buggyj** [comment]
Yes application/x-bclip type is an improvement.

The `@linkURL` contains the absolute file path of the image. Howerver if the image is located in a sub directory or in the same directory as the tiddlywiki it is better to use a relative path, so the `@sublink()` macro with convert the absolute file path to a relative path in this case.
